### ISSUE TITLE
Python gsed: can't read file

### ISSUE THREAD

**Issue by kelvinMusalula** [landtechnologies/reformation#4] opened 2019-10-29 16:39 UTC
Hi, I keep getting the following error when running the reform script.

> gsed: can't read /Users/kelvinmusalula/.pyenv/versions/3.8.0/bin/watchman-make: No such file or directory

This happens error comes under Python section.

**Comment by Milesjpool** [comment] 2019-10-31 11:42
This was caused by the Python-spec not installing new packages.

Resolved by PR #5

**Closed by Milesjpool** 2019-10-31 11:42 UTC
